# Generated by Django 4.2.10 on 2026-03-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrialDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('under_review', 'تحت الفحص'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='under_review', max_length=20, verbose_name='الحالة')),
                ('filing_date', models.DateField(verbose_name='تاريخ الإيداع')),
                ('decision_date', models.DateField(blank=True, null=True, verbose_name='تاريخ القرار')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النشر عن القبول')),
                ('publication_number', models.CharField(blank=True, max_length=100, verbose_name='عدد الجريدة')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسجيل')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='رقم التسجيل')),
                ('rejection_reasons', models.TextField(blank=True, verbose_name='أسباب الرفض')),
                ('appeal_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التظلم')),
                ('appeal_hearing_date', models.DateField(blank=True, null=True, verbose_name='تاريخ جلسة التظلم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='اسم النموذج')),
                ('description', models.TextField(blank=True, verbose_name='وصف النموذج')),
                ('image', models.ImageField(blank=True, null=True, upload_to='designs/', verbose_name='صورة النموذج')),
                ('number', models.CharField(max_length=100, verbose_name='رقم النموذج')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trademark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('under_review', 'تحت الفحص'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='under_review', max_length=20, verbose_name='الحالة')),
                ('filing_date', models.DateField(verbose_name='تاريخ الإيداع')),
                ('decision_date', models.DateField(blank=True, null=True, verbose_name='تاريخ القرار')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النشر عن القبول')),
                ('publication_number', models.CharField(blank=True, max_length=100, verbose_name='عدد الجريدة')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسجيل')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='رقم التسجيل')),
                ('rejection_reasons', models.TextField(blank=True, verbose_name='أسباب الرفض')),
                ('appeal_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التظلم')),
                ('appeal_hearing_date', models.DateField(blank=True, null=True, verbose_name='تاريخ جلسة التظلم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='اسم العلامة التجارية')),
                ('image', models.ImageField(blank=True, null=True, upload_to='trademarks/', verbose_name='صورة العلامة')),
                ('number', models.CharField(max_length=100, verbose_name='رقم العلامة')),
                ('categories', models.CharField(blank=True, max_length=255, verbose_name='الفئات (مفصولة بفواصل)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
