# Generated by Django 6.0.3 on 2026-03-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_alter_industrialdesign_id_alter_trademark_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='الهيئة العامة للعلامات والنماذج الصناعية', max_length=255, verbose_name='عنوان الموقع')),
                ('site_subtitle', models.CharField(default='للعلامات والنماذج الصناعية', max_length=255, verbose_name='وصف الموقع')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='شعار الموقع')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
