# Generated by Django 4.2.10 on 2026-03-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrialdesign',
            name='examination_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم الفحص'),
        ),
        migrations.AddField(
            model_name='industrialdesign',
            name='filing_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم الإيداع'),
        ),
        migrations.AddField(
            model_name='industrialdesign',
            name='publication_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم النشر'),
        ),
        migrations.AddField(
            model_name='industrialdesign',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم التسجيل'),
        ),
        migrations.AddField(
            model_name='trademark',
            name='examination_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم الفحص'),
        ),
        migrations.AddField(
            model_name='trademark',
            name='filing_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم الإيداع'),
        ),
        migrations.AddField(
            model_name='trademark',
            name='publication_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم النشر'),
        ),
        migrations.AddField(
            model_name='trademark',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم التسجيل'),
        ),
        migrations.AlterField(
            model_name='industrialdesign',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
