# Generated by Django 4.2.10 on 2026-04-19 06:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_alter_industrialdesign_id_alter_sitesettings_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industrialdesign',
            options={'ordering': ('-created_at',), 'verbose_name': 'نموذج صناعي', 'verbose_name_plural': 'النماذج الصناعية'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'إعدادات النظام', 'verbose_name_plural': 'إعدادات النظام'},
        ),
        migrations.AlterModelOptions(
            name='trademark',
            options={'ordering': ('-created_at',), 'verbose_name': 'علامة تجارية', 'verbose_name_plural': 'العلامات التجارية'},
        ),
        migrations.AddField(
            model_name='industrialdesign',
            name='additional_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='رسوم إضافية'),
        ),
        migrations.AddField(
            model_name='industrialdesign',
            name='announcement_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإشهار'),
        ),
        migrations.AddField(
            model_name='industrialdesign',
            name='appeal_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='رسوم التظلم'),
        ),
        migrations.AddField(
            model_name='trademark',
            name='additional_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='رسوم إضافية'),
        ),
        migrations.AddField(
            model_name='trademark',
            name='announcement_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإشهار'),
        ),
        migrations.AddField(
            model_name='trademark',
            name='appeal_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='رسوم التظلم'),
        ),
        migrations.AlterField(
            model_name='industrialdesign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='industrialdesign',
            name='examination_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='رسوم الفحص'),
        ),
        migrations.AlterField(
            model_name='industrialdesign',
            name='filing_date',
            field=models.DateField(db_index=True, verbose_name='تاريخ الإيداع'),
        ),
        migrations.AlterField(
            model_name='industrialdesign',
            name='filing_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='رسوم الإيداع'),
        ),
        migrations.AlterField(
            model_name='industrialdesign',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='اسم النموذج الصناعي'),
        ),
        migrations.AlterField(
            model_name='industrialdesign',
            name='number',
            field=models.CharField(db_index=True, max_length=100, verbose_name='رقم النموذج'),
        ),
        migrations.AlterField(
            model_name='industrialdesign',
            name='publication_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='رسوم النشر'),
        ),
        migrations.AlterField(
            model_name='industrialdesign',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='رسوم التسجيل'),
        ),
        migrations.AlterField(
            model_name='industrialdesign',
            name='status',
            field=models.CharField(choices=[('under_review', 'تحت الفحص'), ('accepted', 'قبول'), ('rejected', 'رفض'), ('registered', 'تسجيل')], db_index=True, default='under_review', max_length=20, verbose_name='القرار'),
        ),
        migrations.AlterField(
            model_name='industrialdesign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='شعار النظام'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_subtitle',
            field=models.CharField(default='إدارة محلية متكاملة للعلامات التجارية والنماذج الصناعية', max_length=255, verbose_name='وصف مختصر'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_title',
            field=models.CharField(default='نظام إدارة العلامات والنماذج الصناعية', max_length=255, verbose_name='عنوان النظام'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='categories',
            field=models.CharField(blank=True, max_length=255, verbose_name='فئات العلامة'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='examination_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='رسوم الفحص'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='filing_date',
            field=models.DateField(db_index=True, verbose_name='تاريخ الإيداع'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='filing_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='رسوم الإيداع'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='اسم العلامة التجارية'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='number',
            field=models.CharField(db_index=True, max_length=100, verbose_name='رقم العلامة'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='publication_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='رسوم النشر'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='رسوم التسجيل'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='status',
            field=models.CharField(choices=[('under_review', 'تحت الفحص'), ('accepted', 'قبول'), ('rejected', 'رفض'), ('registered', 'تسجيل')], db_index=True, default='under_review', max_length=20, verbose_name='القرار'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
    ]
