# Generated by Django 6.0.3 on 2026-04-20 11:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_alter_industrialdesign_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrialdesign',
            name='renewal_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='رسوم التجديد'),
        ),
        migrations.AddField(
            model_name='trademark',
            name='renewal_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='رسوم التجديد'),
        ),
    ]
