# Generated by Django 6.0.3 on 2026-04-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_industrialdesign_renewal_fee_trademark_renewal_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrialdesign',
            name='last_renewal_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ آخر تجديد'),
        ),
        migrations.AddField(
            model_name='industrialdesign',
            name='renewal_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد مرات التجديد'),
        ),
        migrations.AddField(
            model_name='trademark',
            name='last_renewal_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ آخر تجديد'),
        ),
        migrations.AddField(
            model_name='trademark',
            name='renewal_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد مرات التجديد'),
        ),
    ]
